namespace WinOptimizationApp.Models;

public sealed record DashboardStatus(
    string WindowsVersion,
    string MachineName,
    string UserName,
    bool IsAdministrator,
    TimeSpan Uptime,
    string SystemDrive,
    long SystemDriveFreeBytes,
    long SystemDriveTotalBytes,
    bool PendingReboot,
    bool WingetAvailable,
    string? LastReportPath,
    string CpuName,
    int ProcessorCount,
    string DotNetRuntime,
    string ProcessArchitecture,
    string OSArchitecture,
    uint MemoryLoadPercent,
    ulong TotalRamBytes,
    ulong AvailableRamBytes,
    ulong TotalPageFileBytes,
    ulong AvailablePageFileBytes,
    IReadOnlyList<DashboardDriveStatus> Drives);
