param(
    [Parameter(Mandatory)]
    [ValidatePattern('^\d+\.\d+\.\d+$')]
    [string]$Version,

    [switch]$Push
)

$ErrorActionPreference = 'Stop'

function Get-RepositoryRoot {
    $directory = Get-Item -LiteralPath (Get-Location)
    while ($null -ne $directory) {
        if (Test-Path -LiteralPath (Join-Path $directory.FullName '.git')) {
            return $directory.FullName
        }

        $directory = $directory.Parent
    }

    throw 'Repository root was not found.'
}

function Assert-CleanWorkingTree {
    $status = git status --porcelain
    if ($status) {
        throw "Working tree must be clean before creating a release. Commit or stash changes first.`n$status"
    }
}

function Assert-NativeCommandSucceeded {
    param(
        [Parameter(Mandatory)]
        [string]$CommandName
    )

    if ($LASTEXITCODE -ne 0) {
        throw "$CommandName failed with exit code $LASTEXITCODE. Release was not created."
    }
}

function Set-ProjectVersion {
    param(
        [Parameter(Mandatory)]
        [string]$ProjectPath,

        [Parameter(Mandatory)]
        [string]$Version
    )

    $fileVersion = "$Version.0"
    $content = Get-Content -LiteralPath $ProjectPath -Raw
    $content = [regex]::Replace($content, '<Version>.*?</Version>', "<Version>$Version</Version>")
    $content = [regex]::Replace($content, '<AssemblyVersion>.*?</AssemblyVersion>', "<AssemblyVersion>$fileVersion</AssemblyVersion>")
    $content = [regex]::Replace($content, '<FileVersion>.*?</FileVersion>', "<FileVersion>$fileVersion</FileVersion>")
    $content = [regex]::Replace($content, '<InformationalVersion>.*?</InformationalVersion>', "<InformationalVersion>$Version</InformationalVersion>")
    [System.IO.File]::WriteAllText($ProjectPath, $content, [System.Text.UTF8Encoding]::new($true))
}

$root = Get-RepositoryRoot
Set-Location -LiteralPath $root

Assert-CleanWorkingTree

$projectPath = Join-Path $root 'src/app/WinOptimizationApp.csproj'
$testProjectPath = Join-Path $root 'src/WinOptimizationApp.Tests/WinOptimizationApp.Tests.csproj'
$tag = "v$Version"
$fileVersion = "$Version.0"

if ((git tag --list $tag)) {
    throw "Git tag already exists: $tag"
}

dotnet test $testProjectPath --configuration Release
Assert-NativeCommandSucceeded -CommandName 'dotnet test'

dotnet restore $projectPath --runtime win-x64
Assert-NativeCommandSucceeded -CommandName 'dotnet restore'

# WinUI XAML compiler output can become incompatible after a .NET or Windows App SDK
# update (for example, stale App.g.i.cs paired with a newly generated App.g.cs).
# Clean only the app's Release intermediates before publishing so both files are
# regenerated by the same compiler version.
dotnet clean $projectPath --configuration Release --runtime win-x64
Assert-NativeCommandSucceeded -CommandName 'dotnet clean'

dotnet publish $projectPath --configuration Release --runtime win-x64 --self-contained true `
    "-p:Version=$Version" `
    "-p:AssemblyVersion=$fileVersion" `
    "-p:FileVersion=$fileVersion" `
    "-p:InformationalVersion=$Version"
Assert-NativeCommandSucceeded -CommandName 'dotnet publish'

Set-ProjectVersion -ProjectPath $projectPath -Version $Version
git add $projectPath
Assert-NativeCommandSucceeded -CommandName 'git add'
git commit -m "Release $tag"
Assert-NativeCommandSucceeded -CommandName 'git commit'
git tag -a $tag -m "Release $tag"
Assert-NativeCommandSucceeded -CommandName 'git tag'

if ($Push) {
    git push origin HEAD
    Assert-NativeCommandSucceeded -CommandName 'git push branch'
    git push origin $tag
    Assert-NativeCommandSucceeded -CommandName 'git push tag'
    Write-Host "Pushed release commit and tag $tag. GitHub Actions will build and publish the Windows release." -ForegroundColor Green
}
else {
    Write-Host "Release commit and tag $tag were created locally." -ForegroundColor Green
    Write-Host "Push with: git push origin HEAD; git push origin $tag"
}
